<input type="hidden" name="student_type" :value="form.student_type">
<input type="hidden" name="amis_student_id" :value="form.amis_student_id">
<input type="hidden" name="learning_mode" :value="form.learning_mode">
<input type="hidden" name="timezone" :value="form.timezone">
<input type="hidden" name="grade_level" :value="form.grade_level">
<input type="hidden" name="lrn" :value="form.lrn">
<input type="hidden" name="last_name" :value="form.last_name">
<input type="hidden" name="first_name" :value="form.first_name">
<input type="hidden" name="middle_name" :value="form.middle_name">
<input type="hidden" name="suffix" :value="form.suffix">
<input type="hidden" name="gender" :value="form.gender">
<input type="hidden" name="date_of_birth" :value="form.date_of_birth">
<input type="hidden" name="place_of_birth" :value="form.place_of_birth">
<input type="hidden" name="religion" :value="form.religion">
<input type="hidden" name="ethnicity" :value="form.ethnicity">
<input type="hidden" name="country" :value="form.country">
<input type="hidden" name="street_address" :value="form.street_address">
<input type="hidden" name="postal_code" :value="form.postal_code">
<input type="hidden" name="address" :value="compiledPresentAddress">
<input type="hidden" name="mobile_country_code" :value="form.mobile_country_code">
<input type="hidden" name="mobile_number" :value="form.mobile_number">
<input type="hidden" name="father_last_name" :value="form.father_last_name">
<input type="hidden" name="father_first_name" :value="form.father_first_name">
<input type="hidden" name="father_middle_name" :value="form.father_middle_name">
<input type="hidden" name="father_occupation" :value="form.father_occupation">
<input type="hidden" name="mother_last_name" :value="form.mother_last_name">
<input type="hidden" name="mother_first_name" :value="form.mother_first_name">
<input type="hidden" name="mother_middle_name" :value="form.mother_middle_name">
<input type="hidden" name="mother_occupation" :value="form.mother_occupation">
<input type="hidden" name="home_address" :value="compiledHomeAddress">
<input type="hidden" name="home_street_address" :value="form.home_street_address">
<input type="hidden" name="home_postal_code" :value="form.home_postal_code">
<input type="hidden" name="parent_country_code" :value="form.parent_country_code">
<input type="hidden" name="parent_mobile" :value="form.parent_mobile">
<input type="hidden" name="parent_email" :value="form.parent_email">
<input type="hidden" name="referral_source" :value="form.referral_source">
<input type="hidden" name="medical_has_concern" :value="form.medical_has_concern">
<input type="hidden" name="psych_testing" :value="form.psych_testing">
<input type="hidden" name="prescription_med" :value="form.prescription_med">
<input type="hidden" name="allergies" :value="form.allergies">
<input type="hidden" name="current_medications" :value="form.current_medications">
<input type="hidden" name="health_conditions" :value="form.health_conditions">
<input type="hidden" name="emergency_instructions" :value="form.emergency_instructions">
<input type="hidden" name="medical_history" :value="form.medical_history">
<input type="hidden" name="med_explanation" :value="form.med_explanation">
<input type="hidden" name="family_physician" :value="form.family_physician">
<input type="hidden" name="physician_phone" :value="form.physician_phone">
<input type="hidden" name="emergency_name" :value="form.emergency_name">
<input type="hidden" name="emergency_relationship" :value="form.emergency_relationship">
<input type="hidden" name="emergency_phone" :value="form.emergency_phone">
<input type="hidden" name="school_year" value="2026-2027">
<input type="hidden" name="agreed_to_data_privacy" :value="form.agreed_to_data_privacy ? '1' : ''">
<input type="hidden" name="agreed_to_terms" :value="form.agreed_to_terms ? '1' : ''">
<input type="hidden" name="agreed_to_fee_policy" :value="form.agreed_to_fee_policy ? '1' : ''">
